### ISSUE TITLE
Use Envoy for deployments

### ISSUE THREAD

**Issue by sebastiandedeyne** [sebastiandedeyne/sebastiandedeyne.com#42]

**Comment by LarBearrr** [comment]
Hi Sebastian, I found this repo after reading [your post](https://sebastiandedeyne.com/christoph-rumpel-on-rebuilding-his-site-with-laravel) and I am intrigued about your Envoy script. You mention in the README that you deploy with zero downtime using this script. Does this mean you have basically replicated that the Envoyer SaaS is doing for us? If so, where can I find a copy of the script?

Thanks!
Larry

**Comment by sebastiandedeyne** [comment]
Hi Larry,

The script is right here in the repo: https://github.com/sebastiandedeyne/sebastiandedeyne.com/blob/master/envoy.blade.php

It's a simplified version of what's described in this blog post: https://mattstauffer.com/blog/how-to-set-up-your-laravel-application-for-zero-downtime-envoyer-capistrano-deploys/

Hope that helps!
