### ISSUE TITLE
Environment = production by default sends Analytics pageviews to your account

### ISSUE THREAD

**Issue by mgustafsson1** [sebastiandedeyne/sebastiandedeyne.com#49]
Hi there,

I cloned this repository today and got it running on my local machine.
After a while I realised I was sending Analytics hits to your account. Sorry about that!

https://github.com/sebastiandedeyne/sebastiandedeyne.com/blob/master/resources/views/layouts/app.blade.php#L35 checks for the production environment, but since there's no .env file, Laravel defaults to production in config/app.

So if you see any weird host names (*.app) in your reports, my apologies :/
If you know how/if you want to handle this and want me to send a PR, please let me know.

Regards from Germany,
Mike

**Comment by sebastiandedeyne** [comment]
Hi!

Thanks for reporting, don't sweat it, didn't really take account of the idea of people really using this repo :D

I moved the actual analytics ID to a env/config value which is cleaner anyway, so this won't happen anymore :)
